server:
  port: 10086
spring:
  application:
    name: itcast-eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10087/eureka
  server:
    eviction-interval-timer-in-ms: 5000